python perSample_preprocess_framework.py newProject \
     --working_dir /home/tonya/test_scanpy_jordan_08032026/test_B2107 \
     --save_prefix testSample_1_independent_analysis \
     --filtered_feature_bc_matrix /mnt/IM_drive/Jordan_Abbott/parse_1M_cell_cardiac_surgery_Tcell_data_01072025/parse_trailmaker_demux_pipeline_output_02162026/WTA_output/output_combined/B2048/DGE_filtered/ \
     --sample_name B2107 \
     --platform parse \
     --convertEnsembl \
     --metadata sex=male age=0.02 "study group"="2 - Neonatal Control" "surgical palliation stage"="Newborn - Control" thymectomy=total race=asian ethnicity="Not Hispanic or Latino" \
     --seed 42 \
     --threads 5 \
     --min_cells_expressed 0 \
     --min_unique_genes 300 \
     --min_umi_counts 500 \
     --mito_contam 10.0 \
     --min_complexity 0.80 \
     --mito_regex "^MT-" \
     --ribo_regex "RPL" "RPS" \
     --dbl_rate 0.03 \
     --removeDoublets \
     --cell_cycle_model human \
     --n_hvgs 2000 \
     --hvg_ignore "^IG[HKL]([VJ]|V[IVX]+|D[0-9])" \
     --pca_var_change 0.01 \
     --neighbors 30 \
     --resolutions 0.2 0.4 0.6 0.7 0.8 0.9 1.0 1.1 1.2 \
     --dist_metric euclidean \
     --top_genes_per_cluster_to_plot 5 \
     --core_genes_to_plot CD3D CD3E CD4 CD8A CD8B CD19 MS4A1 CD79A CD79B \
     
